language: python
python: 3.6
sudo: required

services:
  - docker

before_install:
  - docker pull httpd:alpine
  - docker pull quay.io/teknoradio.org/authenticator
  - docker ps -a

script:
  - docker build --cache-from quay.io/teknoradio.org/authenticator -t teknoradio/authenticator .

notifications:
  email : false


